### ISSUE TITLE
Testing firmware

### ISSUE THREAD

**Issue by t0mhaines** [dwyl/smart-home-firmware#1]
We need to learn how to properly test firmware and what's actually *possible* to test.

Nerves does have testing support, but not every library we will use will do.

We also need to build a working `.travis.yml` file that supports testing our firmware

**Comment by t0mhaines** [comment]
There doesn't seem to be a recognised way of unit testing the hardware side of nerves. Some people mock hardware using things like [tty0tty](https://github.com/lcgamboa/tty0tty) but that requires a lot of knowledge of Unix and Linux *that I don't have*.

I'll write tests for all the pure Elixir parts of the application, although for I deliberately made this firmware as thin as possible (Its mostly glue code between a Phoenix channel and a NFC library) I'm not sure how much of this I'll be able to do

**Comment by t0mhaines** [comment]
Trying to launch tests launches the entire application with it.... we're using named processes so it crashes if we try and launch the same process twice :/

José Valim recommends being able to name your processes on an [Elixir Forum Post](https://elixirforum.com/t/mix-test-launches-entire-app/22013/6?u=t0mh)

> In my opinion, not starting your application in your tests because you want to manually start a process with the same name is somewhat a bad practice. Instead, I would make sure my API allows processes to be started with a custom name, so you do:
> 
> Worker.start_link(:my_name_during_test, ...)
> And I tend to use the test name as the name of the process itself:
> 
> test "my test", config do
>   Worker.start_link(config.test, ...)
> end
> This works nicely if you are starting the process from setup too.

So looks like I've got some refactoring to do...

**Comment by t0mhaines** [comment]
Another good writeup by michalmuskala, who's on the Ecto core team:

> One thing to additionally consider is testing. We’re spoiled in Elixir by the concurrency, so whenever I’m writing systems, I’m thinking how can I test them concurrently. This usually also turns out to be helpful when later scaling the system, but that’s another story.
>
>Even, if I ultimately will run the process registered under a local name, I will rarely register the name directly in start_link - instead I will accept an argument with a name. This can be later used to pass the name from the supervisor to create a named actor for the production system and integration testing. At the same time, this allows easily spawning additional processes in tests for unit testing the particular process. This is a bit more verbose, because it requires passing in the process name/pid as an additional argument to the functions, but this isn’t that big price to be paid and can be worked around as well (the simplest solution being a default argument).

https://elixirforum.com/t/is-giving-a-genserver-module-as-name-a-good-practice/12261/4?u=t0mh

**Comment by t0mhaines** [comment]
All the firmware "internals" now have tests, but anything on the "boundry" -e.g. NFC reader & Socket callbacks are not.

Socket callbacks *should* be possible...

**Comment by nelsonic** [comment]
@th0mas if possible, please try and run the tests on Travis-CI as a reliable third party check.
(_if you get stuck please open issues with the specific things you face and I will try and help_)

**Comment by t0mhaines** [comment]
@nelsonic Please try your CI magic on this - I can't get both tests and coverage to work

**Comment by nelsonic** [comment]
The first step will be getting it running on my `localhost` (_or local hardware_) so that I know what I'm debugging on Travis. 👍 
I will take a look at it Monday morning. 📆

**Comment by nelsonic** [comment]
It appears that Travis is failing to compile `scenic_driver_glfw`:
https://travis-ci.com/github/dwyl/smart-home-firmware/builds/177031095#L286
![image](https://user-images.githubusercontent.com/194400/88396417-69270f00-cdba-11ea-95e3-6f97320fa1b0.png)

Going to try and add it to the Travis-CI VM: https://github.com/boydm/scenic_driver_glfw#installing-on-ubuntu

**Comment by nelsonic** [comment]
https://travis-ci.com/github/dwyl/smart-home-firmware/builds/177034398#L257
```
E: Command line option 'y' [from -y] is not understood in combination with the other options.
```
![image](https://user-images.githubusercontent.com/194400/88397245-94f6c480-cdbb-11ea-9517-181803f778ab.png)

~~Removing it now.~~
Actually, I didn't include the **`install`** keyword on the line. let's try that first!

**Comment by nelsonic** [comment]
https://travis-ci.com/github/dwyl/smart-home-firmware/builds/177034982#L208
```
E: Unable to locate package libglew2.0
E: Couldn't find any package by glob 'libglew2.0'
E: Couldn't find any package by regex 'libglew2.0'
```

![image](https://user-images.githubusercontent.com/194400/88397789-5d3c4c80-cdbc-11ea-9911-e1646eea9236.png)

Reading: https://packages.ubuntu.com/search?keywords=libglew2.0 
![libglew2-bionic](https://user-images.githubusercontent.com/194400/88398295-1ac73f80-cdbd-11ea-8413-8facf9ad5caf.png)

Going to update the distro to Bionic.

**Comment by nelsonic** [comment]
Apparently, **`sudo`** is required: (_otherwise we get "Permission denied" error_) 
https://travis-ci.com/github/dwyl/smart-home-firmware/jobs/364631847#L227

![image](https://user-images.githubusercontent.com/194400/88398684-a17c1c80-cdbd-11ea-8b10-8f1a06461713.png)

**Comment by nelsonic** [comment]
Ok, so the dependencies are all installed, but `mix setup` is not defined.
https://travis-ci.com/github/dwyl/smart-home-firmware/builds/177036800#L717
![image](https://user-images.githubusercontent.com/194400/88400321-12bccf00-cdc0-11ea-9ba6-4c9cdcd3be67.png)

You will see the same error if you attempt to run `mix setup` on your Mac:
```
Generated smart_home_firmware app
** (Mix) The task "setup" could not be found
```
Removing it from `.travis.yml`

**Comment by nelsonic** [comment]
Looks like we have progress: [![Build Status](https://travis-ci.com/dwyl/smart-home-firmware.svg?branch=master)](https://travis-ci.com/dwyl/smart-home-firmware)
https://travis-ci.com/github/dwyl/smart-home-firmware/builds/177039695

![image](https://user-images.githubusercontent.com/194400/88401262-6a0f6f00-cdc1-11ea-9f1d-d9fb05580b41.png)

:shipit:

**Comment by nelsonic** [comment]
@th0mas back to you. 
[![codecov.io](https://img.shields.io/codecov/c/github/dwyl/smart-home-firmware/master.svg?style=flat-square)](http://codecov.io/github/dwyl/smart-home-firmware?branch=master) 
(_totally get that it's "WIP"_) 👍

**Comment by t0mhaines** [comment]
Trying to use GPIO on travis breaks the test. 

*This works on my mac, it seems to fallback to a stub implementation*

![image](https://user-images.githubusercontent.com/9089056/88690106-3733e680-d0f3-11ea-8ae6-197a136d9117.png)

**Comment by t0mhaines** [comment]
Going to spend some time working on integration tests with the heroku hub sever instance....

**Comment by t0mhaines** [comment]
Going to cheat on some of these tests and remove `display/` from our coverage...

This only contains presentation logic, **no** business logic - which is tested elsewhere. Theres no testing framework/guide for scenic and mocking an *entire* graphics library for ~4 tests seems extreme

**Comment by nelsonic** [comment]
@th0mas that seems reasonable _for now_. 👍 
But in the future we would prefer to have some kind of test for the display to check that it's not going haywire or breaking. 💭
