### ISSUE TITLE
Wait for Heroku warmup before starting tests

### ISSUE THREAD

**Issue by t0mhaines** [dwyl/smart-home-firmware#17]
Tests using our heroku-hosted hub fail with timeouts if we don't warm-up our Heroku instance before starting the test suite.

E.g.
![](https://user-images.githubusercontent.com/194400/91282299-13f76800-e781-11ea-8c7e-8242b81b5ad5.png)

We need to `CURl` a request to our hub server in our `.travis.yml`

**Comment by nelsonic** [comment]
@th0mas thanks for opening this issue and fixing. 👍
