### ISSUE TITLE
Switch to `phoenix_gen_socket_client`

### ISSUE THREAD

**Issue by t0mhaines** [dwyl/smart-home-firmware#5]
We probably want to switch our Phoenix socket client out for a few reasons:

+ `phoenix_gen_socket_client` has a `TestSocket` that means we can run integration tests against this library
+ More complete documentation
+  lower level OTP model that will work better for our use case

**Comment by t0mhaines** [comment]
Implemented in 0459086.

Also took this opportunity to refractor the hub client so its a bit nicer to understand now

**Comment by nelsonic** [comment]
@th0mas great simplification. 🙌
